services:
  backend:
    build:
      context: .
      target: development-image
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src/
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:15.7-alpine3.20"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: wmate_db
    healthcheck:
      test: "exit 0"