"""init

Revision ID: 9cbebc872bd6
Revises: 
Create Date: 2024-10-01 18:56:02.473263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbebc872bd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='breeds_schema'
    )
    op.create_table('kittens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds_schema.breeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittens_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kittens', schema='kittens_schema')
    op.drop_table('breeds', schema='breeds_schema')
    # ### end Alembic commands ###
